### ISSUE TITLE
Build Level 01

### ISSUE THREAD

**Issue by plexsoup** [plexsoup/GWJ55#18]
![CrimSound_Level_01](https://user-images.githubusercontent.com/8674767/224885642-1932002d-97d8-487b-89e1-41a6801f13bf.png)

**Comment by Crims0nBunnY** [comment]
![levelsdesignedVersion1](https://user-images.githubusercontent.com/107008367/224916399-c9cdb0c6-23a4-4697-a3d2-033b5e73c33c.png)

**Comment by plexsoup** [comment]
I'll probably build this in three sections, as separate levels. Bottom left, top left and large right.
That'll make the build process a bit easier, and the resource load a bit lighter in-game.

![level01_mockup_section2](https://user-images.githubusercontent.com/8674767/225085200-ad1f51fe-e65b-42ce-9269-7405b2bae958.png)


![level01_mockup_section1](https://user-images.githubusercontent.com/8674767/225085218-1c23dcde-e059-42eb-a940-02315a63b86c.png)


![level01_mockup_section3](https://user-images.githubusercontent.com/8674767/225085213-f44eff26-7e9f-49e1-b7b0-9493eed7da68.png)

**Comment by Crims0nBunnY** [comment]
In general: It think we should have one or two shapes that come back on a very reoccuring basis.. not only to make building the level more easy, but also to have a reliable shape if we lack the time to build more... I was thinking something along side modulable drawers or bookshelves, since I feel they would work very well in a tilemap behavior and not be too shocking


Bottom Left: The bottom left is like a living room (i kinda saw the cat sleeping on the couch "waking up" and starting the level) So something like couches or TVs and pillows could work very well.
The very left of the bottom left part, the part where you exit from at the end of the level should be like the door to outside/garden.

Big Right: For this part I think we want to go for something more bathroom oriented? There's a lot of water so perhaps bathtups and rolled up towels, giant faucets and shower heads, giant toothbrushes or toothpaste tubes for the longer platforms..

**Comment by Crims0nBunnY** [comment]
The top left: This would be the attic... so chests, and cobwebs, old creaky planks, ladders, trapdoors, dusty books, dusty mirror(broken or not, doesn't neeed to be reflective)

**Comment by plexsoup** [comment]
Living Room, Bathroom, Attic. Got it. Thanks.

**Comment by plexsoup** [comment]
LivingRoom.tscn, Attic.tscn, and BathRoom.tscn are all ready for playtesting.

**Comment by plexsoup** [comment]
Redid all three with 67% scale and smaller tiles.

**Comment by plexsoup** [comment]
![levelsdesignedVersion1](https://user-images.githubusercontent.com/8674767/225898456-186daadc-b4fc-4305-9e05-6753eb831a88.png)
